// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview An AI agent that analyzes appraisal feedback and generates insights for HR recruiters.
 *
 * - analyzeAppraisalFeedback - A function that analyzes appraisal feedback and generates insights.
 * - AnalyzeAppraisalFeedbackInput - The input type for the analyzeAppraisalFeedback function.
 * - AnalyzeAppraisalFeedbackOutput - The return type for the analyzeAppraisalFeedback function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AnalyzeAppraisalFeedbackInputSchema = z.object({
  employeeName: z.string().describe('The name of the employee.'),
  jobTitle: z.string().describe('The job title of the employee.'),
  feedbackText: z.string().describe('The appraisal feedback text.'),
});
export type AnalyzeAppraisalFeedbackInput = z.infer<typeof AnalyzeAppraisalFeedbackInputSchema>;

const AnalyzeAppraisalFeedbackOutputSchema = z.object({
  summary: z.string().describe('A short summary of the appraisal feedback.'),
  keyInsights: z.string().describe('Key insights extracted from the appraisal feedback.'),
  recommendations: z.string().describe('Recommendations based on the appraisal feedback.'),
});
export type AnalyzeAppraisalFeedbackOutput = z.infer<typeof AnalyzeAppraisalFeedbackOutputSchema>;

export async function analyzeAppraisalFeedback(
  input: AnalyzeAppraisalFeedbackInput
): Promise<AnalyzeAppraisalFeedbackOutput> {
  return analyzeAppraisalFeedbackFlow(input);
}

const prompt = ai.definePrompt({
  name: 'analyzeAppraisalFeedbackPrompt',
  input: {schema: AnalyzeAppraisalFeedbackInputSchema},
  output: {schema: AnalyzeAppraisalFeedbackOutputSchema},
  prompt: `You are an AI assistant specializing in analyzing appraisal feedback for HR recruiters. Analyze the provided feedback and generate a concise summary, key insights, and recommendations.

Employee Name: {{{employeeName}}}
Job Title: {{{jobTitle}}}
Feedback Text: {{{feedbackText}}}

Summary:
Key Insights:
Recommendations: `,
});

const analyzeAppraisalFeedbackFlow = ai.defineFlow(
  {
    name: 'analyzeAppraisalFeedbackFlow',
    inputSchema: AnalyzeAppraisalFeedbackInputSchema,
    outputSchema: AnalyzeAppraisalFeedbackOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
