// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview An AI agent that rates a resume based on job preferences and uploaded documents.
 *
 * - rateResume - A function that handles the resume rating process.
 * - RateResumeInput - The input type for the rateResume function.
 * - RateResumeOutput - The return type for the rateResume function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const RateResumeInputSchema = z.object({
  jobField: z.string().describe('The preferred job field.'),
  resumeDataUri: z
    .string()
    .describe(
      'The resume file as a data URI that must include a MIME type and use Base64 encoding. Expected format: \'data:<mimetype>;base64,<encoded_data>\'.' // The resume file as a data URI.
    ),
  certificatesDataUris: z
    .array(z.string())
    .describe(
      'An array of certificate files as data URIs that must include a MIME type and use Base64 encoding. Expected format: \'data:<mimetype>;base64,<encoded_data>\'.'
    ),
  workExperience: z.string().describe('A description of relevant work experience.'),
});
export type RateResumeInput = z.infer<typeof RateResumeInputSchema>;

const RateResumeOutputSchema = z.object({
  score: z
    .number()
    .describe('The resume score out of 100%.')
    .min(0)
    .max(100),
  aiComments: z.string().describe('AI generated comments on the resume.'),
});
export type RateResumeOutput = z.infer<typeof RateResumeOutputSchema>;

export async function rateResume(input: RateResumeInput): Promise<RateResumeOutput> {
  return rateResumeFlow(input);
}

const prompt = ai.definePrompt({
  name: 'rateResumePrompt',
  input: {schema: RateResumeInputSchema},
  output: {schema: RateResumeOutputSchema},
  prompt: `You are an expert HR assistant specializing in evaluating resumes. Rate the resume out of 100 based on the selected job field, uploaded certificates, and work experience.

Job Field: {{{jobField}}}
Resume: {{media url=resumeDataUri}}
Certificates: {{#each certificatesDataUris}}{{media url=this}}{{/each}}
Work Experience: {{{workExperience}}}

Provide a score out of 100 and AI-generated comments on the resume.

Score: 
AI Comments: `,
});

const rateResumeFlow = ai.defineFlow(
  {
    name: 'rateResumeFlow',
    inputSchema: RateResumeInputSchema,
    outputSchema: RateResumeOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
